# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ingredient.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ingredient.proto',
  package='ingredient',
  syntax='proto3',
  serialized_options=b'\n\030com.wmaiouiru.ingredientB\nIngredientP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10ingredient.proto\x12\ningredient\"N\n\nIngredient\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x11\n\tphoto_url\x18\x04 \x01(\t\"E\n\x17\x43reateIngredientRequest\x12*\n\ningredient\x18\x01 \x01(\x0b\x32\x16.ingredient.Ingredient\"F\n\x18\x43reateIngredientResponse\x12*\n\ningredient\x18\x01 \x01(\x0b\x32\x16.ingredient.Ingredient\"\"\n\x14GetIngredientRequest\x12\n\n\x02id\x18\x01 \x01(\t\"C\n\x15GetIngredientResponse\x12*\n\ningredient\x18\x01 \x01(\x0b\x32\x16.ingredient.Ingredient\"\x17\n\x15ListIngredientRequest\"D\n\x16ListIngredientResponse\x12*\n\ningredient\x18\x01 \x01(\x0b\x32\x16.ingredient.Ingredient2\xa7\x02\n\x11IngredientService\x12_\n\x10\x43reateIngredient\x12#.ingredient.CreateIngredientRequest\x1a$.ingredient.CreateIngredientResponse\"\x00\x12V\n\rGetIngredient\x12 .ingredient.GetIngredientRequest\x1a!.ingredient.GetIngredientResponse\"\x00\x12Y\n\x0eListIngredient\x12!.ingredient.ListIngredientRequest\x1a\".ingredient.ListIngredientResponse\"\x00\x42(\n\x18\x63om.wmaiouiru.ingredientB\nIngredientP\x01\x62\x06proto3'
)




_INGREDIENT = _descriptor.Descriptor(
  name='Ingredient',
  full_name='ingredient.Ingredient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ingredient.Ingredient.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ingredient.Ingredient.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='ingredient.Ingredient.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='photo_url', full_name='ingredient.Ingredient.photo_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=110,
)


_CREATEINGREDIENTREQUEST = _descriptor.Descriptor(
  name='CreateIngredientRequest',
  full_name='ingredient.CreateIngredientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredient', full_name='ingredient.CreateIngredientRequest.ingredient', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=181,
)


_CREATEINGREDIENTRESPONSE = _descriptor.Descriptor(
  name='CreateIngredientResponse',
  full_name='ingredient.CreateIngredientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredient', full_name='ingredient.CreateIngredientResponse.ingredient', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=253,
)


_GETINGREDIENTREQUEST = _descriptor.Descriptor(
  name='GetIngredientRequest',
  full_name='ingredient.GetIngredientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ingredient.GetIngredientRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=289,
)


_GETINGREDIENTRESPONSE = _descriptor.Descriptor(
  name='GetIngredientResponse',
  full_name='ingredient.GetIngredientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredient', full_name='ingredient.GetIngredientResponse.ingredient', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=358,
)


_LISTINGREDIENTREQUEST = _descriptor.Descriptor(
  name='ListIngredientRequest',
  full_name='ingredient.ListIngredientRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=383,
)


_LISTINGREDIENTRESPONSE = _descriptor.Descriptor(
  name='ListIngredientResponse',
  full_name='ingredient.ListIngredientResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingredient', full_name='ingredient.ListIngredientResponse.ingredient', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=453,
)

_CREATEINGREDIENTREQUEST.fields_by_name['ingredient'].message_type = _INGREDIENT
_CREATEINGREDIENTRESPONSE.fields_by_name['ingredient'].message_type = _INGREDIENT
_GETINGREDIENTRESPONSE.fields_by_name['ingredient'].message_type = _INGREDIENT
_LISTINGREDIENTRESPONSE.fields_by_name['ingredient'].message_type = _INGREDIENT
DESCRIPTOR.message_types_by_name['Ingredient'] = _INGREDIENT
DESCRIPTOR.message_types_by_name['CreateIngredientRequest'] = _CREATEINGREDIENTREQUEST
DESCRIPTOR.message_types_by_name['CreateIngredientResponse'] = _CREATEINGREDIENTRESPONSE
DESCRIPTOR.message_types_by_name['GetIngredientRequest'] = _GETINGREDIENTREQUEST
DESCRIPTOR.message_types_by_name['GetIngredientResponse'] = _GETINGREDIENTRESPONSE
DESCRIPTOR.message_types_by_name['ListIngredientRequest'] = _LISTINGREDIENTREQUEST
DESCRIPTOR.message_types_by_name['ListIngredientResponse'] = _LISTINGREDIENTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ingredient = _reflection.GeneratedProtocolMessageType('Ingredient', (_message.Message,), {
  'DESCRIPTOR' : _INGREDIENT,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.Ingredient)
  })
_sym_db.RegisterMessage(Ingredient)

CreateIngredientRequest = _reflection.GeneratedProtocolMessageType('CreateIngredientRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINGREDIENTREQUEST,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.CreateIngredientRequest)
  })
_sym_db.RegisterMessage(CreateIngredientRequest)

CreateIngredientResponse = _reflection.GeneratedProtocolMessageType('CreateIngredientResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEINGREDIENTRESPONSE,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.CreateIngredientResponse)
  })
_sym_db.RegisterMessage(CreateIngredientResponse)

GetIngredientRequest = _reflection.GeneratedProtocolMessageType('GetIngredientRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETINGREDIENTREQUEST,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.GetIngredientRequest)
  })
_sym_db.RegisterMessage(GetIngredientRequest)

GetIngredientResponse = _reflection.GeneratedProtocolMessageType('GetIngredientResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETINGREDIENTRESPONSE,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.GetIngredientResponse)
  })
_sym_db.RegisterMessage(GetIngredientResponse)

ListIngredientRequest = _reflection.GeneratedProtocolMessageType('ListIngredientRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTINGREDIENTREQUEST,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.ListIngredientRequest)
  })
_sym_db.RegisterMessage(ListIngredientRequest)

ListIngredientResponse = _reflection.GeneratedProtocolMessageType('ListIngredientResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTINGREDIENTRESPONSE,
  '__module__' : 'ingredient_pb2'
  # @@protoc_insertion_point(class_scope:ingredient.ListIngredientResponse)
  })
_sym_db.RegisterMessage(ListIngredientResponse)


DESCRIPTOR._options = None

_INGREDIENTSERVICE = _descriptor.ServiceDescriptor(
  name='IngredientService',
  full_name='ingredient.IngredientService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=456,
  serialized_end=751,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateIngredient',
    full_name='ingredient.IngredientService.CreateIngredient',
    index=0,
    containing_service=None,
    input_type=_CREATEINGREDIENTREQUEST,
    output_type=_CREATEINGREDIENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetIngredient',
    full_name='ingredient.IngredientService.GetIngredient',
    index=1,
    containing_service=None,
    input_type=_GETINGREDIENTREQUEST,
    output_type=_GETINGREDIENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListIngredient',
    full_name='ingredient.IngredientService.ListIngredient',
    index=2,
    containing_service=None,
    input_type=_LISTINGREDIENTREQUEST,
    output_type=_LISTINGREDIENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INGREDIENTSERVICE)

DESCRIPTOR.services_by_name['IngredientService'] = _INGREDIENTSERVICE

# @@protoc_insertion_point(module_scope)
